Add support for private locations
checkly/terraform-provider-checkly pull request #160
Opened 2022-06-01 21:47 UTC by pilimartinez

## Affected Components
* [X] Resources
* [X] Tests
* [X] Docs
* [ ] Tooling
* [ ] Other

## Pre-Requisites
* [X] Terraform code is formatted with `terraform fmt`
* [X] Go code is formatted with `go fmt`
* [X] `plan` & `apply` command of `demo/main.tf` file do not produce diffs

## Notes for the Reviewer

-Add CRUD methods
-New tests
-Update docs and examples

> Resolves #159

2022-06-08 18:04 UTC, ianaya89 requested changes

2022-06-08 18:04 UTC, ianaya89 commented on checkly/provider.go
> +			"checkly_private_locations":    resourcePrivateLocations(),
This should be singular "location"

2022-06-08 18:04 UTC, ianaya89 commented on checkly/resource_private_locations.go
> +		Create: resourcePrivateLocationsCreate,
Same for this method names

2022-06-08 18:04 UTC, ianaya89 commented on checkly/resource_private_locations.go
> +	d.Set("raw_key", result.Keys[0].RawKey)
I think will be better to name this property `key`

2022-06-08 18:04 UTC, ianaya89 commented on docs/resources/private_locations.md
> +---
Did you create this with the docs script or was manually added?

2022-06-08 18:04 UTC, ianaya89 commented on checkly/resource_private_locations.go
> +			"name": {
All these fields need to have the `Description` property

2022-06-08 19:04 UTC, pilimartinez commented on checkly/integration_test.go
> +//go:build integration
It appears every time I save, I think it comes from the // +build integration thats on the next line. That came from the main branch and that's why I left it there but if its not necessary I can remove it (and that will prevent the //go:build integration to appear on the code)

2022-06-21 17:07 UTC, ianaya89 submitted a review, later dismissed

2022-06-21 21:59 UTC, merged